// Generated by Skyramp v1.3.37 on 2026-08-10 00:54:06.16220912 +0000 UTC m=+957.981724397
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output exercise_logs_wger_react_ui.spec.ts \
// 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/wger/wger/wger/.skyramp/exercise_logs_wger_react_ui_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(154000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:80/en/user/login");
    await page.locator("#id_login").fill("admin");
    await page.locator("#id_password").fill("adminadmin");
    await page.getByRole("button", { name: "Login" }).click();
    await expect(page).toHaveURL(/\/en\/dashboard/);
    await page.goto("http://localhost/en/exercise/1/view");
    await expect(page).toHaveURL(/\/en\/exercise\/1\/view/);
    expect(errors).toHaveLength(0);
});
