# Generated by Skyramp v1.3.37 on 2026-08-10 00:50:05.184281938 +0000 UTC m=+717.003797034
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output exercise_logs_date_ordering_integration_test.py \
# 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/wger/wger/wger/tests/skyramp/scenario_exercise-logs-date-ordering.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_web = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://web:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    exercise = "9"

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "date": "2023-06-01T08:00:00Z",
        "exercise": 1,
        "weight": "60.00",
        "weight_unit": 2
    }'''

    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_web,
        path="/api/v2/workoutlog/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers,
        data_override={"exercise": exercise}
    )

    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") is not None
    assert int(skyramp.get_response_value(endpoint_2_POST_response, "exercise")) == 9
    assert skyramp.get_response_value(endpoint_2_POST_response, "weight") == "60.00"
    assert int(skyramp.get_response_value(endpoint_2_POST_response, "weight_unit")) == 2

    # Request Body
    endpoint_2_POST_1_request_body = r'''{
        "date": "2024-01-15T10:00:00Z",
        "exercise": 1,
        "weight": "80.00",
        "weight_unit": 2
    }'''

    # Execute Request
    endpoint_2_POST_1_response = client.send_request(
        url=URL_web,
        path="/api/v2/workoutlog/",
        method="POST",
        body=endpoint_2_POST_1_request_body,
        headers=headers,
        data_override={"exercise": skyramp.get_response_value(endpoint_2_POST_response, "exercise")}
    )

    # Generated Assertions
    assert endpoint_2_POST_1_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_1_response, "id") is not None
    assert skyramp.get_response_value(endpoint_2_POST_1_response, "exercise") == skyramp.get_response_value(endpoint_2_POST_response, "exercise")
    assert skyramp.get_response_value(endpoint_2_POST_1_response, "weight") == "80.00"
    assert int(skyramp.get_response_value(endpoint_2_POST_1_response, "weight_unit")) == 2

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_web,
        path="/api/v2/exercise/{exercise}/logs/",
        method="GET",
        headers=headers,
        path_params={"exercise": skyramp.get_response_value(endpoint_2_POST_response, "exercise")}
    )

    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200
    # Verify at least 1 log entry returned for this exercise
    assert skyramp.get_response_value(endpoint_1_GET_response, "0") is not None
    # Verify the first entry's exercise FK matches the queried exercise
    assert skyramp.get_response_value(endpoint_1_GET_response, "0.exercise") == skyramp.get_response_value(endpoint_2_POST_response, "exercise")
    # Verify newest-first ordering: first item date >= second item date
    assert skyramp.get_response_value(endpoint_1_GET_response, "0.date") >= skyramp.get_response_value(endpoint_1_GET_response, "1.date")

    # Execute Request
    endpoint_3_DELETE_response = client.send_request(
        url=URL_web,
        path="/api/v2/workoutlog/{workoutlog}/",
        method="DELETE",
        headers=headers,
        path_params={"workoutlog": skyramp.get_response_value(endpoint_2_POST_response, "id")}
    )

    # Generated Assertions
    assert endpoint_3_DELETE_response.status_code == 204

    # Execute Request
    endpoint_3_DELETE_1_response = client.send_request(
        url=URL_web,
        path="/api/v2/workoutlog/{workoutlog}/",
        method="DELETE",
        headers=headers,
        path_params={"workoutlog": skyramp.get_response_value(endpoint_2_POST_1_response, "id")}
    )

    # Generated Assertions
    assert endpoint_3_DELETE_1_response.status_code == 204


if __name__ == "__main__":
    test_integration()
