# Generated by Skyramp v1.3.37 on 2026-08-10 00:59:56.278540672 +0000 UTC m=+450.267628188
# Command: skyramp generate contract rest http://web:8000/api/v2/ingredient/ \
# 		--api-schema http://localhost/api/v2/schema \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output ingredient_regex_alternation_contract_test.py \
# 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--query-params name__regex=Testzutat|Ingredient \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://web:8000")

# contract test for /api/v2/ingredient/ GET
def test_ingredient_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_ingredient_GET_response_body = r'''{
        "count": 2,
        "results": [
            {
                "carbohydrates": "12.500",
                "created": "2026-08-10T00:59:56Z",
                "energy": 52,
                "fat": "0.200",
                "id": 2,
                "language": 2,
                "last_imported": "2026-08-10T00:59:56Z",
                "last_update": "2026-08-10T00:59:56Z",
                "name": "Ingredient, test, 2, organic, raw",
                "protein": "1.100",
                "uuid": "0111cdbb-3498-4cf7-9a41-66416f6c9d0a",
                "weight_units": [
                    {
                        "gram": 100.0,
                        "id": 1,
                        "ingredient": 2,
                        "name": "g",
                        "uuid": "7938941e-7179-4464-a72d-789264752342"
                    }
                ]
            }
        ]
    }'''

    # Execute Request
    ingredient_GET_response = client.send_request(
        url=URL,
        path="/api/v2/ingredient/",
        method="GET",
        headers=headers,
        query_params={"name__regex": "Testzutat|Ingredient"}
    )

    # Generated Assertions
    assert ingredient_GET_response.status_code == 200
    assert skyramp.check_schema(ingredient_GET_response, expected_ingredient_GET_response_body)
    assert skyramp.get_response_value(ingredient_GET_response, "count") is not None
    assert skyramp.get_response_value(ingredient_GET_response, "results.0.carbohydrates") is not None
    assert skyramp.get_response_value(ingredient_GET_response, "results.0.created") is not None
    assert skyramp.get_response_value(ingredient_GET_response, "count") >= 2
    assert skyramp.get_response_value(ingredient_GET_response, "results.0.id") > 0
    assert skyramp.get_response_value(ingredient_GET_response, "results.0.name") is not None
    assert skyramp.get_response_value(ingredient_GET_response, "results.0.language") > 0


if __name__ == "__main__":
    test_ingredient_get()
