# Generated by Skyramp v1.3.37 on 2026-08-10 01:00:15.718988095 +0000 UTC m=+469.708075621
# Command: skyramp generate contract rest http://web:8000/api/v2/ingredient/ \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output ingredient_regex_invalid_pattern_contract_test.py \
# 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--query-params name__regex=[invalid \
# 		--response-status-code 400 \
# 		--runtime local

# Import of required libraries
import skyramp
import os


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://web:8000")

# contract test for /api/v2/ingredient/ GET
def test_ingredient_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    ingredient_GET_response = client.send_request(
        url=URL,
        path="/api/v2/ingredient/",
        method="GET",
        headers=headers,
        query_params={"name__regex": "[invalid"}
    )

    # Generated Assertions
    assert ingredient_GET_response.status_code == 400
    assert skyramp.get_response_value(ingredient_GET_response, "results") is None


if __name__ == "__main__":
    test_ingredient_get()
