# Generated by Skyramp v1.3.37 on 2026-08-10 01:00:19.33108592 +0000 UTC m=+473.320173454
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output ingredient_regex_anchored_search_integration_test.py \
# 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/wger/wger/wger/tests/skyramp/scenario_ingredient-regex-anchored-search-workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_web = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://web:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_web,
        path="/api/v2/ingredient/",
        method="GET",
        headers=headers,
        query_params={"name__regex": ["^Ingredient"]}
    )

    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_1_GET_response, "count") == 1
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.0.id") == 2
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.0.name") == "Ingredient, test, 2, organic, raw"
    assert skyramp.get_response_value(endpoint_1_GET_response, "results.1") is None

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_web,
        path="/api/v2/ingredient/{ingredient}/",
        method="GET",
        headers=headers,
        path_params={"ingredient": skyramp.get_response_value(endpoint_1_GET_response, "results.0.id")}
    )

    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_2_GET_response, "id") == skyramp.get_response_value(endpoint_1_GET_response, "results.0.id")
    assert skyramp.get_response_value(endpoint_2_GET_response, "name") == "Ingredient, test, 2, organic, raw"
    assert skyramp.get_response_value(endpoint_2_GET_response, "id") > 0


if __name__ == "__main__":
    test_integration()
