# Generated by Skyramp v1.3.37 on 2026-08-10 00:50:32.682888305 +0000 UTC m=+744.502403391
# Command: skyramp generate contract rest http://web:8000/api/v2/exercise/{id}/logs/ \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--path-params id=99999 \
# 		--provider \
# 		--response-status-code 404 \
# 		--runtime local

# Import of required libraries
import skyramp
import os


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://web:8000")

# contract test for /api/v2/exercise/{id}/logs/ GET
def test_logs_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "99999"

    # Execute Request
    logs_GET_response = client.send_request(
        url=URL,
        path="/api/v2/exercise/{id}/logs/",
        method="GET",
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert logs_GET_response.status_code == 404
    assert skyramp.get_response_value(logs_GET_response, "detail") is not None


if __name__ == "__main__":
    test_logs_get()
