# Generated by Skyramp v1.3.37 on 2026-08-10 01:52:08.180089305 +0000 UTC m=+540.412180662
# Command: skyramp generate contract rest http://web:8000/api/v2/public-templates/ \
# 		--api-schema http://localhost/api/v2/schema \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://web:8000")

# contract test for /api/v2/public-templates/ GET
def test_public_templates_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_public_templates_GET_response_body = r'''{
        "count": 0,
        "next": null,
        "previous": null,
        "results": []
    }'''

    # Execute Request
    public_templates_GET_response = client.send_request(
        url=URL,
        path="/api/v2/public-templates/",
        method="GET",
        headers=headers,
        query_params={
            "created": None,
            "description": None,
            "limit": None,
            "name": None,
            "offset": None,
            "ordering": None
        }
    )

    # Generated Assertions
    assert public_templates_GET_response.status_code == 200
    assert skyramp.check_schema(public_templates_GET_response, expected_public_templates_GET_response_body)
    assert skyramp.get_response_value(public_templates_GET_response, "count") is not None
    assert skyramp.get_response_value(public_templates_GET_response, "count") >= 0


if __name__ == "__main__":
    test_public_templates_get()
