# Generated by Skyramp v1.3.37 on 2026-08-10 01:52:58.354025546 +0000 UTC m=+590.586116883
# Command: skyramp generate contract rest http://web:8000/api/v2/public-templates/{id}/ \
# 		--api-schema http://localhost/api/v2/schema \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output public_templates_detail_author_field_contract_test.py \
# 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--parent-request-data id={"name": "Public Template Author Test", "start": "2024-01-01", "end": "2024-06-30", "is_template": true, "is_public": true} \
# 		--parent-status-code id=201 \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://web:8000")

# contract test for /api/v2/public-templates/{id}/ GET
def test_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Create a public template to get a valid ID for the contract test
    create_request_body = r'''{
        "name": "Author Contract Test Template",
        "start": "2024-01-01",
        "end": "2024-06-30",
        "is_template": true,
        "is_public": true
    }'''
    create_response = client.send_request(
        url=URL,
        path="/api/v2/routine/",
        method="POST",
        body=create_request_body,
        headers=headers
    )
    assert create_response.status_code == 201
    id = skyramp.get_response_value(create_response, "id")

    # Expected Response Body
    expected_id_GET_response_body = r'''{
        "author": {"username": "test", "email": "test@example.com", "date_joined": "2024-01-01T00:00:00Z"},
        "created": "2024-01-01T00:00:00Z",
        "end": "2024-06-30",
        "id": 1,
        "start": "2024-01-01"
    }'''

    # Execute Request
    id_GET_response = client.send_request(
        url=URL,
        path="/api/v2/public-templates/{id}/",
        method="GET",
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert id_GET_response.status_code == 200
    assert skyramp.check_schema(id_GET_response, expected_id_GET_response_body)
    assert skyramp.get_response_value(id_GET_response, "id") == id
    assert skyramp.get_response_value(id_GET_response, "author") is not None
    assert skyramp.get_response_value(id_GET_response, "author.username") is not None
    assert skyramp.get_response_value(id_GET_response, "author.email") is not None
    assert "@" in str(skyramp.get_response_value(id_GET_response, "author.email"))
    assert skyramp.get_response_value(id_GET_response, "author.date_joined") is not None
    assert skyramp.get_response_value(id_GET_response, "created") is not None
    assert skyramp.get_response_value(id_GET_response, "end") == "2024-06-30"
    assert skyramp.get_response_value(id_GET_response, "start") == "2024-01-01"

    # Cleanup
    client.send_request(url=URL, path="/api/v2/routine/{id}/", method="DELETE", headers=headers, path_params={"id": id})


if __name__ == "__main__":
    test_id_get()
