# Generated by Skyramp v1.3.37 on 2026-08-10 01:53:21.848580767 +0000 UTC m=+614.080672124
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output routine_author_cross_user_verification_integration_test.py \
# 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/wger/wger/wger/tests/skyramp/scenario_routine-author-cross-user-verification.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_web = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://web:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "end": "2024-06-30",
        "is_public": true,
        "is_template": true,
        "name": "AuthTest",
        "start": "2024-01-01"
    }'''

    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_web,
        path="/api/v2/routine/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers,
        data_override={"name": skyramp.unique_suffix("AuthTest")}
    )

    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") is not None
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") > 0
    assert skyramp.get_response_value(endpoint_2_POST_response, "is_public") == True
    assert skyramp.get_response_value(endpoint_2_POST_response, "is_template") == True
    assert skyramp.get_response_value(endpoint_2_POST_response, "start") == "2024-01-01"
    assert skyramp.get_response_value(endpoint_2_POST_response, "end") == "2024-06-30"
    assert skyramp.get_response_value(endpoint_2_POST_response, "author") is not None
    assert skyramp.get_response_value(endpoint_2_POST_response, "author.username") is not None

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_web,
        path="/api/v2/public-templates/{public-templates}/",
        method="GET",
        headers=headers,
        path_params={"public-templates": skyramp.get_response_value(endpoint_2_POST_response, "id")}
    )

    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_1_GET_response, "id") == skyramp.get_response_value(endpoint_2_POST_response, "id")
    assert skyramp.get_response_value(endpoint_1_GET_response, "is_public") == True
    assert skyramp.get_response_value(endpoint_1_GET_response, "is_template") == True
    assert skyramp.get_response_value(endpoint_1_GET_response, "author") is not None
    assert skyramp.get_response_value(endpoint_1_GET_response, "author.username") is not None
    assert skyramp.get_response_value(endpoint_1_GET_response, "author.email") is not None
    assert "@" in str(skyramp.get_response_value(endpoint_1_GET_response, "author.email"))
    assert skyramp.get_response_value(endpoint_1_GET_response, "author.date_joined") is not None

    # Execute Request
    endpoint_3_DELETE_response = client.send_request(
        url=URL_web,
        path="/api/v2/routine/{routine}/",
        method="DELETE",
        headers=headers,
        path_params={"routine": skyramp.get_response_value(endpoint_2_POST_response, "id")}
    )

    # Generated Assertions
    assert endpoint_3_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
