# Generated by Skyramp v1.3.37 on 2026-08-09 22:22:17.442546755 +0000 UTC m=+363.822062876
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output statistics_inclusive_upper_bound_integration_test.py \
# 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/wger/wger/wger/tests/skyramp/scenario_statistics-inclusive-upper-bound.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_web = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://web:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "date": "2024-01-31",
        "weight": "80.00"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_web,
        path="/api/v2/weightentry/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "weight") == "80.00"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_web,
        path="/api/v2/weightentry/statistics/",
        method="GET",
        headers=headers,
        query_params={
            "date_from": "2024-01-01",
            "date_to": "2024-01-31"
        }
    )

    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_2_GET_response, "count") == 1
    assert skyramp.get_response_value(endpoint_2_GET_response, "min") == "80.00"
    assert skyramp.get_response_value(endpoint_2_GET_response, "max") == "80.00"
    assert skyramp.get_response_value(endpoint_2_GET_response, "date_from") == "2024-01-01"
    assert skyramp.get_response_value(endpoint_2_GET_response, "date_to") == "2024-01-31"

    # Execute Request
    endpoint_3_DELETE_response = client.send_request(
        url=URL_web,
        path="/api/v2/weightentry/{weightentry}/",
        method="DELETE",
        headers=headers,
        path_params={"weightentry": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )

    # Generated Assertions
    assert endpoint_3_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
