# Generated by Skyramp v1.3.37 on 2026-08-09 22:22:19.505661973 +0000 UTC m=+365.885178084
# Command: skyramp generate integration rest \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--output statistics_aggregation_computation_integration_test.py \
# 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/wger/wger/wger/tests/skyramp/scenario_statistics-aggregation-computation.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_web = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://web:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "date": "2024-01-10",
        "weight": "82.50"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_web,
        path="/api/v2/weightentry/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "weight") == "82.50"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") > 0

    # Request Body
    endpoint_1_POST_1_request_body = r'''{
        "date": "2024-01-20",
        "weight": "80.20"
    }'''

    # Execute Request
    endpoint_1_POST_1_response = client.send_request(
        url=URL_web,
        path="/api/v2/weightentry/",
        method="POST",
        body=endpoint_1_POST_1_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_1_POST_1_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "weight") == "80.20"
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "id") > 0

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_web,
        path="/api/v2/weightentry/statistics/",
        method="GET",
        headers=headers,
        query_params={
            "date_from": "2024-01-01",
            "date_to": "2024-02-01"
        }
    )

    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200
    assert skyramp.get_response_value(endpoint_2_GET_response, "count") >= 2
    assert float(skyramp.get_response_value(endpoint_2_GET_response, "min")) <= 80.20
    assert float(skyramp.get_response_value(endpoint_2_GET_response, "max")) >= 82.50
    assert skyramp.get_response_value(endpoint_2_GET_response, "date_from") == "2024-01-01"
    assert skyramp.get_response_value(endpoint_2_GET_response, "date_to") == "2024-02-01"

    # Execute Request
    endpoint_3_DELETE_response = client.send_request(
        url=URL_web,
        path="/api/v2/weightentry/{weightentry}/",
        method="DELETE",
        headers=headers,
        path_params={"weightentry": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )

    # Generated Assertions
    assert endpoint_3_DELETE_response.status_code == 204

    # Execute Request
    endpoint_3_DELETE_1_response = client.send_request(
        url=URL_web,
        path="/api/v2/weightentry/{weightentry}/",
        method="DELETE",
        headers=headers,
        path_params={"weightentry": skyramp.get_response_value(endpoint_1_POST_1_response, "id")}
    )

    # Generated Assertions
    assert endpoint_3_DELETE_1_response.status_code == 204


if __name__ == "__main__":
    test_integration()
