# Generated by Skyramp v1.3.37 on 2026-08-09 22:21:46.043646056 +0000 UTC m=+332.423162157
# Command: skyramp generate contract rest http://web:8000/api/v2/weightentry/statistics/ \
# 		--api-schema http://localhost/api/v2/schema \
# 		--auth-type Token \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output statistics_empty_range_no_entries_contract_test.py \
# 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--query-params date_from=2000-01-01,date_to=2000-01-02 \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://web:8000")

# contract test for /api/v2/weightentry/statistics/ GET
def test_statistics_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Token " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_statistics_GET_response_body = r'''{
        "date_from": "2000-01-01",
        "date_to": "2000-01-02",
        "count": 0,
        "min": null,
        "max": null,
        "average": null
    }'''

    # Execute Request
    statistics_GET_response = client.send_request(
        url=URL,
        path="/api/v2/weightentry/statistics/",
        method="GET",
        headers=headers,
        query_params={
            "date_from": "2000-01-01",
            "date_to": "2000-01-02"
        }
    )

    # Generated Assertions
    assert statistics_GET_response.status_code == 200
    assert skyramp.check_schema(statistics_GET_response, expected_statistics_GET_response_body)
    assert skyramp.get_response_value(statistics_GET_response, "count") == 0
    assert skyramp.get_response_value(statistics_GET_response, "date_from") == "2000-01-01"
    assert skyramp.get_response_value(statistics_GET_response, "date_to") == "2000-01-02"
    assert skyramp.get_response_value(statistics_GET_response, "min") is None
    assert skyramp.get_response_value(statistics_GET_response, "max") is None
    assert skyramp.get_response_value(statistics_GET_response, "average") is None


if __name__ == "__main__":
    test_statistics_get()
