// Generated by Skyramp v1.3.32 on 2026-07-05 01:49:36.566128584 +0000 UTC m=+490.170805162
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output-dir /home/runner/work/wger/wger/wger/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/wger/wger/wger/.skyramp/measurement_list_route_trace_1.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(70000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (e) => errors.push(e));

    await page.goto("http://localhost/en/user/login");
    await page.locator("#id_login").fill("admin");
    await page.locator("#id_password").fill("adminadmin");
    await page.getByRole("button", { name: "Login" }).click();
    await page.goto("http://localhost/en/measurement/list");
    await expect(page).toHaveURL(/\/en\/measurement\/list$/);
    await expect(page.locator("#page-title")).toHaveText("Measurements");
    expect(errors).toHaveLength(0);
});
